# Generated by Django 4.2.3 on 2023-07-25 11:09

from django.conf import settings
from django.db import migrations, models
import printjobs.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('printjobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Customer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='peices',
            new_name='quantity',
        ),
        migrations.AlterField(
            model_name='order',
            name='staff',
            field=models.ForeignKey(limit_choices_to={'is_admin': True}, on_delete=models.SET(printjobs.models.set_user_inactive), to=settings.AUTH_USER_MODEL),
        ),
    ]
