# Generated by Django 4.2.3 on 2023-07-25 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printjobs', '0002_rename_customer_order_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='printjobs.jobtype')),
            ],
        ),
    ]
