# Generated by Django 4.2.3 on 2023-07-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printjobs', '0003_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='rate',
            field=models.FloatField(default=0.0),
        ),
    ]
