# Generated by Django 4.2.3 on 2023-07-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printjobs', '0004_rate_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Name',
            field=models.CharField(db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PND', 'PENDING'), ('INP', 'INPROGRESS'), ('CMP', 'COMPLETED')], db_index=True, default='PND', max_length=3),
        ),
    ]
