# Generated by Django 4.2.3 on 2023-07-27 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import printjobs.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('printjobs', '0005_alter_customer_name_alter_customer_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ip',
            field=models.CharField(default='172.168.1.1', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], db_index=True, default='New', max_length=10),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.DateTimeField(auto_created=True)),
                ('payment_id', models.CharField(max_length=100)),
                ('payment_method', models.CharField(max_length=100)),
                ('amount_paid', models.CharField(max_length=100)),
                ('tax', models.FloatField()),
                ('ip', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printjobs.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order_price', models.FloatField()),
                ('ordered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printjobs.customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printjobs.order')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printjobs.payment')),
                ('staff', models.ForeignKey(limit_choices_to={'is_admin': True}, on_delete=models.SET(printjobs.models.set_user_inactive), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
