# Generated by Django 4.2.3 on 2023-07-27 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printjobs', '0007_rename_status_payment_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='user',
            new_name='customer',
        ),
    ]
