# Generated by Django 4.2.3 on 2023-08-05 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import printjobs.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('printjobs', '0009_rename_customer_orderjob_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], db_index=True, default='New', max_length=10),
        ),
        migrations.AlterField(
            model_name='orderjob',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='printjobs.order'),
        ),
        migrations.CreateModel(
            name='Print',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('status', models.CharField(choices=[('In_progress', 'In_progress'), ('Completed', 'Completed'), ('Print_error', 'Print_error')], db_index=True, default='In_progress', max_length=11)),
                ('collected', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(auto_now=True)),
                ('order_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='printjobs.order')),
                ('printed_by', models.ForeignKey(limit_choices_to={'is_admin': True}, on_delete=models.SET(printjobs.models.set_user_inactive), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
