# Generated by Django 4.2.3 on 2023-08-07 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printjobs', '0010_alter_order_status_alter_orderjob_order_print'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderjob',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printjobs.order'),
        ),
    ]
