# Generated by Django 4.2.3 on 2023-08-07 10:03

from django.conf import settings
from django.db import migrations, models
import printjobs.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('printjobs', '0011_alter_orderjob_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='confirmed_by',
            field=models.ForeignKey(default=1, limit_choices_to={'is_admin': True}, on_delete=models.SET(printjobs.models.set_user_inactive), to=settings.AUTH_USER_MODEL),
        ),
    ]
