# Generated by Django 4.2.3 on 2023-08-14 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printjobs', '0015_alter_order_options_alter_joborder_total_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('access_place_order_page', 'Can access the place order page')],
            },
        ),
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
    ]
