# Generated by Django 4.2.3 on 2023-08-14 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printjobs', '0016_grouppermissions_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grouppermissions',
            options={'permissions': [('access_place_order_page', 'Can access the place order page'), ('delete_placed_order_page', 'Can delete placed order')]},
        ),
    ]
