# Generated by Django 4.2.3 on 2023-08-14 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printjobs', '0021_alter_grouppermissions_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
