# Generated by Django 4.2.3 on 2023-08-15 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printjobs', '0022_alter_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtype',
            name='rate',
            field=models.FloatField(default=1.0),
        ),
        migrations.DeleteModel(
            name='Rate',
        ),
    ]
