# Generated by Django 4.2.3 on 2023-08-15 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printjobs', '0023_jobtype_rate_delete_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborder',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='joborder',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='printjobs.payment'),
        ),
    ]
