# Generated by Django 4.2.3 on 2023-08-15 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printjobs', '0024_joborder_paid_alter_joborder_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborder',
            name='job_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='printjobs.jobtype'),
        ),
    ]
